
export const KnType = {
  Map: 'Map',
  Vector: 'Vector',
  Knot: 'Knot',
  Word: 'Word',
  Quote: 'Quote',
  Quasiquote: 'Quasiquote',
  Unquote: 'Unquote',
  UnquoteSplicing: 'UnquoteSplicing',
  Symbol: 'Symbol',
  String: 'String',
  Number: 'Number',
  Boolean: 'Boolean',
  Nil: 'Nil',
  Unknown: 'Unknown',
  OperandStack: 'OperandStack',
  LambdaFunc: 'LambdaFunc',
  HostFunc: 'HostFunc',
  Property: 'Property',
  Subscript: 'Subscript',

  Table: 'Table',
  TableMetadata: 'TableMetadata',
  FieldStorageMetadata: 'FieldStorageMetadata',
  FieldPropMetadata: 'FieldPropMetadata',
  CalcPropMetadata: 'CalcPropMetadata',
  PropertyFunc: 'PropertyFunc',
  MethodMetadata: 'MethodMetadata',
  MethodFunc: 'MethodFunc',

  Continuation: 'Continuation',
}